[project]
name = "workout-tracker"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "asgiref==3.11.0",
    "django==5.2.9",
    "psycopg==3.3.2",
    "sqlparse==0.5.5",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.1.0",
]
